In [1]:
import numpy as np


In [2]:
#creat an array from a list
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:

#creat an array with regularly spaced values
a_range = np.arange(0,10)
print(a_range)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
#creat an array with evenly spaced values
a_linspace = np.linspace(0,10,5)
print(a_linspace)

[ 0.   2.5  5.   7.5 10. ]


In [11]:
random_uniform=np.random.rand(5)
print(random_uniform)

[0.15341449 0.81536455 0.57590844 0.15647904 0.51137837]


In [13]:
random_normal=np.random.randn(10)
print(random_normal)

[ 0.4982355   2.18953379  0.90448265 -1.07827344  1.01572169 -0.11086246
  3.59378497  0.5626714   0.03772327 -0.58631784]


In [23]:
arr=np.array([[1,2,3],[4,5,6]])
shape=np.shape(arr)
print(shape)
print(arr)
#dtype=np.dtype(arr)
size=np.size(arr)
print(shape)
print(size)

(2, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [19]:
#dtype=np.dtype(arr)
#print(dtype)

In [25]:
a=np.array([1,5,8,9,5,9,6,8])
first_element=a[0]
print(first_element)
sliced_array=a[1:4]
print(sliced_array)

1
[5 8 9]


In [27]:
# reshaping and manipulating array
arr=np.array([[1,2,3],[4,5,6]])
reshaped_arr=np.reshape(arr,(3,2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
transposed_arr=np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
#filtering
a=np.array([1,5,8,9,5,9,6,8])
filtering_arr=a[a>7]
print(filtering_arr)

[8 9 9 8]
